project_id = "ehirqsqkfnjuuvzthsrx"

[functions.create-invoice]
verify_jwt = true

[functions.add-clinic]
verify_jwt = true

[functions.set-subscription-cancel]
verify_jwt = true

[functions.invoice-status]
verify_jwt = true

[functions.nextpay-webhook]
verify_jwt = false

[functions.billing-cron]
verify_jwt = false
